apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-petclinic-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic-prod
    server: distant-cluster
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/smartinus44/openshift-gitops-getting-started.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
